### PR TITLE
Update to Rails 4.2 / Bootstrap 3

### LINKED ISSUE #14: Upgrade to rails 4.2
I'm willing to do this, but I wanted to ask first if there's any reason not to.

### PR DESCRIPTION
**Pull request by vosechu**
- Update rails in Gemfile
- Run `rake rails:update`
- Fix tests
- Remove attr_accessible from models (but I didn’t put it back in the
  controllers)
- Unfix the lazy loader from BigListController
- Update bootstrap in sass and js
- Remove trailing whitespace
- Remove inline and in-page styles
- Add description for ManyAssets#index
- Fix indenting in index.html.erb
- Fix navbar 
- Remove extra css/js
- Switch to SASS includes per `bootstrap-sass`s whim

Fixes #14

### CODE REVIEW

**Comment by vosechu** [comment]
Please feel free to undo/change anything with no feelings of guilt whatsoever. I hope that my changes kept the project on the right path, but I know that I had to do some CSS changes that may have violated some of the original goals. I assure you, I have no attachment to them whatsoever. :)

**Comment by jasonrclark** [comment]
Noticed that we didn't get the Gemfile.lock updates included here. Blew it away locally to rebuild, but you want to include your local edits on that Chuck?

Ran through and almost all the pages are performing similarly to before, and look as good (or better! :sparkles:) than previously. Excellent!

Only exception is "The Loop" was this minor UI change:

**Rails 3.2**
image

**Rails 4.2**
image


Both of them to include the `<i class="icon-ok"></i>` HTML, so I'm betting something in the CSS updates just isn't showing the checkbox widget. From your spelunking, do you know where that'd be coming from @vosechu?

Once again, :heart: :sparkling_heart: for doing this! It's been lingering on my todo list for quite a while, and refreshing to have it up to date!

**Comment by vosechu** [comment]
Ah! Interesting. Looks like icons changed class from `icon-*` to `glyphicon glyphicon-*`. So `glyphicon glyphicon-ok` or `glyphicon glyphicon-ok-circle` would work awesomely. 

Also, I just did a `bundle update` yesterday so whatever that yields for a Gemfile.lock should work I think.

**Comment by vosechu** [comment]
_he says and then immediately commits his Gemfile.lock anyways_

**Comment by vosechu** [comment]
Also sent in a fix for the glyphicons. Slow day today.

**Comment by jasonrclark** [comment]
:boom: thanks @vosechu!

**Comment by vosechu** [comment]
Of course! Happy to help

**Comment by vosechu** [comment]
Woohoo! Thanks!

**Pull request merged**
